services:
  postgresql:
    container_name: postgres-latest
    image: postgres
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=docker'
      - 'POSTGRES_DB=jira_db'
    networks:
      network:
        ipv4_address: 10.5.0.6

  pgadmin:
    container_name: pgadmin4-latest
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgresql
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=super-bot@bot.ru
      - PGADMIN_DEFAULT_PASSWORD=super-bot
      - PGADMIN_LISTEN_PORT=5454
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      network:
        ipv4_address: 10.5.0.4

  notificationsbot:
    image: ${DOCKER_REGISTRY-}notificationsbot
    build:
      context: NotaficationBot
      dockerfile: Dockerfile
    networks:
      network:
        ipv4_address: 10.5.0.5
    depends_on:
      - postgresql

volumes:
  db:
    driver: local
  pgadmin-data:
    driver: local

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1