services:
  postgresql:
    container_name: postgres-latest
    image: postgres
    expose:
      - "${POSTGRES_EXPOSE_PORTS}"
    ports:
      - ${POSTGRES_PORTS}
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - 'POSTGRES_USER= ${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}'
      - 'POSTGRES_DB= ${POSTGRES_DB}'
    command: -c work_mem=32MB -c shared_buffers=2GB -c maintenance_work_mem=1GB -c full_page_writes=off -c autovacuum=off -c wal_buffers=-1
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}']
      interval: 1s
      timeout: 5s
      retries: 20
    networks:
      - network

  notaficationbot:
    image: ${DOCKER_REGISTRY}/notaficationbot:${TAG}
    ports:
      - ${HTTP_PORTS}
      - ${HTTPS_PORTS}
    networks:
      - network
    depends_on:
      - postgresql
    env_file:
      - .env

volumes:
  db:
    driver: local

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}