name: "Docker Image on tag"

on:
  push:
    tags:
      - "v*"
    # branches:
    #  - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: latest
      ORGANIZATION: vitacore
      PROJECT: notaficationbot

    steps:
    - uses: actions/checkout@v2

    - uses: docker/login-action@v3
      name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v6
      name: Build and push
      with:
        context: ./NotaficationBot
        file: ./NotaficationBot/Dockerfile
        push: true
        tags: |
          ${{ env.ORGANIZATION }}/${{ env.PROJECT }}:${{ env.DOCKER_TAG }}
          ${{ env.ORGANIZATION }}/${{ env.PROJECT }}:${{ github.ref_name }}